Added remote synthesis tool
arnasRad/vits pull request #3
Opened 2023-04-11 06:10 UTC by rokasgie

2023-04-11 16:18 UTC, arnasRad commented on tools/jnotebooks/synthesis_remote/synthesize_audiobook.ipynb
Visokių kodo smulkmenų kaip optimize imports, formatting ir t.t. čia nereview'insiu nes kitame task'e turėsiu viską vis tiek refactorinti, o dauguma kodo matosi iš esamos versijos paimta

2023-04-11 16:57 UTC, arnasRad requested changes
reiktų dar pakeisti kelias vietas kur nurodžiau kad veiktų kodas bet šiaip manau atrodo all good

2023-04-11 16:57 UTC, arnasRad commented on tools/jnotebooks/synthesis_remote/requirements.txt
> +tqdm
dar jupyter reikia

2023-04-11 16:57 UTC, arnasRad commented on tools/jnotebooks/synthesis_remote/synthesize_audiobook.ipynb
> +    "def synthesize_sentences(sentences: List[Sentence], batch_size: int, speed_mult: float):\n",
speed_multipliers šiame notebook nenaudojami bet berods tiesiog kol kas deploy'intas modelis nepalaiko šio parametro?

2023-04-11 16:57 UTC, arnasRad commented on tools/jnotebooks/synthesis_remote/synthesize_audiobook.ipynb
> +    "    sentences = split_paragraph_to_sentences(paragraph)\n",
`paragraph` is undefined

2023-04-11 16:57 UTC, arnasRad commented on tools/jnotebooks/synthesis_remote/synthesize_audiobook.ipynb
> +    "    save_audio(chapter_audio, SAMPLE_RATE, output_dir / f\"{chapter_name}.wav\")\n",
`chapter_name` is undefined

2023-04-11 16:57 UTC, arnasRad commented on tools/jnotebooks/synthesis_remote/synthesize_audiobook.ipynb
> +    "for i, (name, chapter) in enumerate(chapters, start=1):\n",
reikėjo perrašyti cell taip:

```
for i, (name, chapter) in enumerate(chapters, start=1):
    print(f"Synthesizing chapter `{name}` ({i}/{len(chapters)})")

    for paragraph in chapter:
        sentences = split_paragraph_to_sentences(paragraph)
        synthesized_sentences = synthesize_sentences(sentences, BATCH_SIZE, SPEED_MULTIPLIER)

        chapter_audio = concatenate_sentences(synthesized_sentences, SILENCE_BETWEEN_SENTENCES, SILENCE_BETWEEN_PARAGRAPHS)
        save_audio(chapter_audio, SAMPLE_RATE, output_dir / f"{name}.wav")

        srt_entries = srt_entries_from_sentences(synthesized_sentences, SILENCE_BETWEEN_SENTENCES, SILENCE_BETWEEN_PARAGRAPHS)
        save_srt_entries_to_file(srt_entries, output_dir / f"{name}.srt")
```

2023-04-11 16:57 UTC, arnasRad commented on tools/jnotebooks/synthesis_remote/synthesize_audiobook.ipynb
> +    "    outputs = [synthesize(batched_sentences) for batched_sentences in chunked(texts, batch_size)]\n",
`synthesize(batched_sentences)` -> `synthesize(batched_sentences, speed_mult=speed_mult)`

2023-04-11 16:58 UTC, arnasRad commented
Bandau sintezuoti poliarinis ratas audiobook. Jau kurį laiką laukiu response dėl vieno chapter. @rokasgie kai testavai, kiek laiko tau daugmaž užtrukdavo vieną chapter ar visą knygą susintezuoti?

2023-04-12 06:40 UTC, rokasgie commented on tools/jnotebooks/synthesis_remote/synthesize_audiobook.ipynb
> +    "def synthesize_sentences(sentences: List[Sentence], batch_size: int, speed_mult: float):\n",
Dabar jau palaiko

2023-04-12 07:19 UTC, rokasgie commented on tools/jnotebooks/synthesis_remote/synthesize_audiobook.ipynb
> +    "for i, (name, chapter) in enumerate(chapters, start=1):\n",
Tada paragrafai bus išsaugoti atskirai. Parašiau kad būtų kartu per visą chapter

2023-04-12 07:21 UTC, rokasgie commented
> Bandau sintezuoti poliarinis ratas audiobook. Jau kurį laiką laukiu response dėl vieno chapter. @rokasgie kai testavai, kiek laiko tau daugmaž užtrukdavo vieną chapter ar visą knygą susintezuoti?

Visos nesintezavau, nes nepakaks pinigų mum banana dabar. Reikia palaukti kol Tadas grįš ir papildys. Bet iš esmės tai pradžioj pirmas request turėtų ilgai trukti, o paskui jau greičiau. Galima didinti batch size kol leidžia, taip maksimizuosim greitį

2023-04-12 11:14 UTC, rokasgie commented
> Bandau sintezuoti poliarinis ratas audiobook. Jau kurį laiką laukiu response dėl vieno chapter. @rokasgie kai testavai, kiek laiko tau daugmaž užtrukdavo vieną chapter ar visą knygą susintezuoti?

Vienas chapter ~5min priklausomai nuo ilgio. Ateity su Python script bus galima padaryt su futures ir leist per kelis VMus banana nes yra tokia galimybė. Bet Jupyter neveiktų toks manau

2023-04-12 11:15 UTC, rokasgie commented
> > Bandau sintezuoti poliarinis ratas audiobook. Jau kurį laiką laukiu response dėl vieno chapter. @rokasgie kai testavai, kiek laiko tau daugmaž užtrukdavo vieną chapter ar visą knygą susintezuoti?
> 
> Vienas chapter ~5min priklausomai nuo ilgio. Ateity su Python script bus galima padaryt su futures ir leist per kelis VMus banana nes yra tokia galimybė. Bet Jupyter neveiktų toks manau

Dar galma branch size didinti bet jei išpuola ilgas sakinys gali failint dėl memory

2023-04-17 05:57 UTC, arnasRad commented
Kažkodėl meta error kai bandau sintezuoti. Any idea kodėl?

![image](https://user-images.githubusercontent.com/43096239/232395244-612cb5bc-281f-4154-ad1c-d9c9b58249ba.png)

Prieš errors gavau tokius prints:

![image](https://user-images.githubusercontent.com/43096239/232395341-420fe2d1-42d5-4d82-beff-1ca051969e04.png)

2023-04-17 05:57 UTC, arnasRad commented
@rokasgie

2023-04-17 06:52 UTC, rokasgie commented
Panašu, kad kažkoks vidinis erroras banana

2023-04-17, pr, 08:57 arnasRad ***@***.***> rašė:

> @rokasgie <https://github.com/rokasgie>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/arnasRad/vits/pull/3#issuecomment-1510747697>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI2BCPG4TWGFO6CHOVGTZLLXBTLVBANCNFSM6AAAAAAWZZ3ZPA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-22 14:16 UTC, rokasgie commented
@arnasRad  kad negerai su SRT failais?

2023-04-24 07:45 UTC, arnasRad approved these changes

2023-04-24 07:45 UTC, merged